export const listCity = [
  { id: 1, name: "Tỉnh Tuyên Quang" },
  { id: 2, name: "Tỉnh Cao Bằng" },
  { id: 3, name: "Tỉnh Lai Châu" },
  { id: 4, name: "Tỉnh Lào Cai" },
  { id: 5, name: "Tỉnh Thái Nguyên" },
  { id: 6, name: "Tỉnh Điện Biên" },
  { id: 7, name: "Tỉnh Lạng Sơn" },
  { id: 8, name: "Tỉnh Sơn La" },
  { id: 9, name: "Tỉnh Phú Thọ" },
  { id: 10, name: "Tỉnh Bắc Ninh" },
  { id: 11, name: "Tỉnh Quảng Ninh" },
  { id: 12, name: "Thành phố Hà Nội" },
  { id: 13, name: "Thành phố Hải Phòng" },
  { id: 14, name: "Tỉnh Hưng Yên" },
  { id: 15, name: "Tỉnh Ninh Bình" },
  { id: 16, name: "Tỉnh Thanh Hóa" },
  { id: 17, name: "Tỉnh Nghệ An" },
  { id: 18, name: "Tỉnh Hà Tĩnh" },
  { id: 19, name: "Tỉnh Quảng Trị" },
  { id: 20, name: "Thành phố Huế" },
  { id: 21, name: "Thành phố Đà Nẵng" },
  { id: 22, name: "Tỉnh Quảng Ngãi" },
  { id: 23, name: "Tỉnh Gia Lai" },
  { id: 24, name: "Tỉnh Đắk Lắk" },
  { id: 25, name: "Tỉnh Khánh Hòa" },
  { id: 26, name: "Tỉnh Lâm Đồng" },
  { id: 27, name: "Tỉnh Đồng Nai" },
  { id: 28, name: "Tỉnh Tây Ninh" },
  { id: 29, name: "Thành phố Hồ Chí Minh" },
  { id: 30, name: "Tỉnh Đồng Tháp" },
  { id: 31, name: "Tỉnh An Giang" },
  { id: 32, name: "Tỉnh Vĩnh Long" },
  { id: 33, name: "Thành phố Cần Thơ" },
  { id: 34, name: "Tỉnh Cà Mau" },
];
