import "./globals.css";
import { Smooch_Sans } from "next/font/google";
import Providers from "./provider";

const font = Smooch_Sans({
  subsets: ["vietnamese"],
  weight: "500",
});

export const metadata = {
  title: "FUsen Job",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${font.className} w-full antialiased overflow-auto scroll-box`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
